name: finalproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  permission_handler: ^11.0.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.0.8
  flutter_local_notifications: ^17.2.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Tambahkan bagian ini untuk mengimpor gambar dari folder assets/images
  assets:
    - assets/images/cloudy.png
    - assets/images/profile.jpg
